import { Constraint } from '../src/version/constraint'
import { Version } from '../src/version/version'
import matrix from './upstream-constraint-matrix.json'

/**
 * Differential test against upstream's own implementation.
 *
 * The expectations in upstream-constraint-matrix.json were generated by running
 * dflook/terraform-github-actions' `terraform/versions.py` over every
 * combination of operator, bound and version below. Regenerating it after an
 * upstream change is how we detect that our selection logic has drifted from
 * theirs — which matters because version selection decides which binary runs.
 */
interface Case {
  constraint: string
  version: string
  allowed: boolean | string
}

const cases = matrix as Case[]

describe('constraint behaviour matches upstream', () => {
  it('covers a broad matrix', () => {
    expect(cases.length).toBeGreaterThan(400)
  })

  it.each(cases.map((c) => [c.constraint, c.version, c.allowed] as const))(
    '%s against %s → %s',
    (constraint, version, expected) => {
      let actual: boolean | string
      try {
        actual = new Constraint(constraint).isAllowed(new Version(version))
      } catch (error) {
        actual = `error:${(error as Error).constructor.name}`
      }
      expect(actual).toBe(expected)
    }
  )
})
